Feature: To validate the inventory details.

Background: To get the base url deatils
Given url 'https://fives.cga.omnib.manh.com'

Scenario: Adding Item inventory
And path '/inventory/api/inventory/supply/supplyEvent'
*def body = ('data/itemInventory.json')
And Header Content-Type = 'application/json'
And Header Authorization = 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyT3JncyI6WyJmaXZlYmVsb3ciXSwidXNlcl9uYW1lIjoicm9ib3NlcnZpY2UiLCJ1c2VyTG9jYXRpb25zIjpbXSwibG9jYWxlIjoiZW4iLCJleGNsdWRlZFVzZXJCdXNpbmVzc1VuaXRzIjpbXSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9GdW5jdGlvbmFsQWRtaW4iXSwiY2xpZW50X2lkIjoib21uaWNvbXBvbmVudC4xLjAuMCIsInVzZXJUaW1lWm9uZSI6IlVUQyIsImVkZ2UiOjAsImxhcmdlU3RvcmVBY2Nlc3MiOiJ0cnVlIiwic2NvcGUiOlsib21uaSIsImNvbXBvbmVudCJdLCJvcmdhbml6YXRpb24iOiJmaXZlYmVsb3ciLCJhY2Nlc3N0b0FsbEJVcyI6ZmFsc2UsInRlbmFudElkIjoiZml2ZW9zZjExbyIsImV4cCI6MTcxNjkyMTgzMCwidXNlckRlZmF1bHRzIjpbXSwianRpIjoiN2Q2OWZmMTEtZjcxZS00YzQyLTgwZGUtZGQwOGI3YTc2NmQ4IiwidXNlckJ1c2luZXNzVW5pdHMiOltdfQ.aAQaSXzh-LrkW7_ddZt1boO-hx18-hMATOfsdXwUykMQzAznp6cydgbq5MUXOaGaWWjEu786qWmlWV1eyxML_hu-Za7i00oj62Bxs1MbjpgSJXOj4fdJNRC092ssjzX8J4rNRCZ9lgEUyHkvoQ58FkpWV7EWWQy5ZSdLeYUb9Ce-UrJ-kr7HjHpFQPBHiP0CuURAHiJ7TkjFNW4Bns5okMm-DzIDpI7FilM_vveUFL154Ql2fzS6iCUNhGNGMJVeaCZvzSMsSrzapxg-ZoLDIObbZfx5bogSk5l2UWvI8t3arqiJ___3BarVO5QTP1OHwN0hFghCv4LW77uTfoQ9sA'
And request body
When method post 
Then staus 201
And print response